package com.writing.documents;

public enum Status {

	DOCUMENT_FOR_REVIEW, 
	DOCUMENT_FOR_DRAFTING,
	READY_FOR_SUBMISSION,
	DOCUMENTS_SUBMITTED, 
	REJECTED_SUMBISSON, 
	DOCUMENTS_PUBLISHED, 
	ARCHIVED
}
